resqdoc2/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using resqdoc2.Models;
using System.Diagnostics;

namespace resqdoc2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

resqdoc2/Controllers/OcorrenciasController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using resqdoc2.Enums;

using resqdoc2.Models;
using resqdoc2.Models.ResqDoc.Models;

namespace resqdoc2.Controllers
{
    public class OcorrenciasController : Controller
    {
        private readonly Context _context;

        public OcorrenciasController(Context context)
        {
            _context = context;
        }

        // GET: Ocorrencias

        public IActionResult Index(string busca, string filtro)
        {
            // Obtenha todos os registros de ocorrência do banco de dados
            var ocorrencias = _context.Ocorrencia.ToList();

            // Se a pesquisa não estiver vazia e o filtro for "titulo", filtre os resultados pelo título
            if (!string.IsNullOrEmpty(busca) && filtro == "titulo")
            {
                busca = busca.ToLower(); // Converta a pesquisa para minúsculas para tornar a pesquisa insensível a maiúsculas e minúsculas

                ocorrencias = ocorrencias.Where(o =>
                    o.Titulo.ToLower().Contains(busca)
                ).ToList();
            }

            // Se a pesquisa não estiver vazia e o filtro for "cobrade", filtre os resultados pelo Cobrade
            //if (!string.IsNullOrEmpty(busca) && filtro == "cobrade")
            //{
            //    // Converta a entrada em um número inteiro
            //    if (int.TryParse(busca, out int cobrade))
            //    {
            //        ocorrencias = ocorrencias.Where(o =>
            //            o.Cobrade == cobrade
            //        ).ToList();
            //    }
            //}

            return View(ocorrencias);
        }









        // GET: Ocorrencias/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Ocorrencia == null)
            {   
                return NotFound();
            }

            var ocorrencia = await _context.Ocorrencia
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ocorrencia == null)
            {
                return NotFound();
            }

            return View(ocorrencia);
        }

        // GET: Ocorrencias/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Ocorrencias/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Titulo,Gravidade,Data,Cobrade")] Ocorrencia ocorrencia, string Data)
        {
            if (ModelState.IsValid)
            {
                // Converte a string Data em um DateTime
                if (DateTime.TryParseExact(Data, "dd/MM/yyyy", CultureInfo.InvariantCulture, DateTimeStyles.None, out var dataConvertida))
                {
                    // Converte o DateTime para DateOnly
                    ocorrencia.Data = DateOnly.FromDateTime(dataConvertida);

                    _context.Add(ocorrencia);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ModelState.AddModelError("Data", "Formato de data inválido. Use o formato dd/MM/yyyy.");
                }
            }
            return View(ocorrencia);
        }



        // GET: Ocorrencias/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Ocorrencia == null)
            {
                return NotFound();
            }

            var ocorrencia = await _context.Ocorrencia.FindAsync(id);
            if (ocorrencia == null)
            {
                return NotFound();
            }
            return View(ocorrencia);
        }

        // POST: Ocorrencias/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Titulo,Gravidade,DateTime,Cobrade")] Ocorrencia ocorrencia)
        {
            if (id != ocorrencia.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(ocorrencia);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OcorrenciaExists(ocorrencia.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(ocorrencia);
        }

        // GET: Ocorrencias/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Ocorrencia == null)
            {
                return NotFound();
            }

            var ocorrencia = await _context.Ocorrencia
                .FirstOrDefaultAsync(m => m.Id == id);
            if (ocorrencia == null)
            {
                return NotFound();
            }

            return View(ocorrencia);
        }

        // POST: Ocorrencias/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Ocorrencia == null)
            {
                return Problem("Entity set 'Context.Ocorrencia'  is null.");
            }
            var ocorrencia = await _context.Ocorrencia.FindAsync(id);
            if (ocorrencia != null)
            {
                _context.Ocorrencia.Remove(ocorrencia);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OcorrenciaExists(int id)
        {
          return (_context.Ocorrencia?.Any(e => e.Id == id)).GetValueOrDefault();
        }

       
    }
}

resqdoc2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!-- Mashead header-->
<header class="masthead">
    <div class=" container px-3">
        <div class="row gx-5 align-items-center">
            <div class="col-lg-6">
                <!-- Mashead text and app badges-->
                <div class="mb-5 mb-lg-0 text-center text-lg-start">
                    <h1 class="display-1 lh-1 mb-3">Defesa Civil de Chapecó.</h1>
                    <p class="lead fw-normal text-muted mb-5">“A evolução do ser na construção do saber!”</p>
                    <div class="d-flex flex-column flex-lg-row align-items-center">
                        
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <!-- Masthead device mockup feature-->
                <div class="masthead-device-mockup">
                    @*<svg class="circle" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
                        <defs>
                            <linearGradient id="circleGradient" gradientTransform="rotate(45)">
                                <stop class="gradient-start-color" offset="0%"></stop>
                                <stop class="gradient-end-color" offset="100%"></stop>
                            </linearGradient>
                        </defs>
                        <circle cx="50" cy="50" r="50"></circle>
                    </svg><svg class="shape-1 d-none d-sm-block" viewBox="0 0 240.83 240.83" xmlns="http://www.w3.org/2000/svg">
                        <rect x="-32.54" y="78.39" width="305.92" height="84.05" rx="42.03" transform="translate(120.42 -49.88) rotate(45)"></rect>
                        <rect x="-32.54" y="78.39" width="305.92" height="84.05" rx="42.03" transform="translate(-49.88 120.42) rotate(-45)"></rect>
                    </svg><svg class="shape-2 d-none d-sm-block" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg"><circle cx="50" cy="50" r="50"></circle></svg>*@
                    <div class="w-50">
                       
                         <img src="~/logopreto.png" />
                                                   
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Quote/testimonial aside-->
<aside class="text-center bg-gradient-primary-to-secondary">
    <div class=" px-5">
        <div class="row gx-5 justify-content-center">
            <div class="col-xl-8">
                <div class="h2 fs-1 text-white mb-4">"Software desenvolvido a fim de sanar problemas sobre arquivo de documentação da Defesa Civil de Chapecó"</div>
                
            </div>
        </div>
    </div>
</aside>
<!-- App features section-->
<section id="features">
    <div class=" container px-5">
        <div class="row gx-5 align-items-center">
            <div class="col-lg-8 order-lg-1 mb-5 mb-lg-0"> 
                <div class="container-fluid px-5">
                    <div class="row gx-5">
                        <div class="col-md-6 mb-5">
                            <!-- Feature item-->
                            <div class="text-center">
                                <a asp-controller="Ocorrencias" asp-action="Create"><i class="bi-file-earmark-plus icon-feature text-gradient d-block mb-3"></i></a>
                                <h3 class="font-alt">Adicionar</h3>
                                <p class="text-muted mb-0"></p>
                            </div>
                        </div>
                        <div class="col-md-6 mb-5">
                            <!-- Feature item-->
                            <div class="text-center">
                                <a asp-controller="Ocorrencias" asp-action="Search"><i class="bi-search icon-feature text-gradient d-block mb-3"></i></a>
                                <h3 class="font-alt">Buscar</h3>
                                <p class="text-muted mb-0"></p>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                       
                    </div>
                </div>
            </div>
            <div class="col-lg-4 order-lg-0">
                <!-- Features section device mockup-->
                <div class="features-device-mockup">
                    <svg class="circle" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg">
                        <defs>
                            <linearGradient id="circleGradient" gradientTransform="rotate(45)">
                                <stop class="gradient-start-color" offset="0%"></stop>
                                <stop class="gradient-end-color" offset="100%"></stop>
                            </linearGradient>
                        </defs>
                        <circle cx="50" cy="50" r="50"></circle>
                    </svg><svg class="shape-1 d-none d-sm-block" viewBox="0 0 240.83 240.83" xmlns="http://www.w3.org/2000/svg">
                        <rect x="-32.54" y="78.39" width="305.92" height="84.05" rx="42.03" transform="translate(120.42 -49.88) rotate(45)"></rect>
                        <rect x="-32.54" y="78.39" width="305.92" height="84.05" rx="42.03" transform="translate(-49.88 120.42) rotate(-45)"></rect>
                    </svg><svg class="shape-2 d-none d-sm-block" viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg"><circle cx="50" cy="50" r="50"></circle></svg>
                    <div class="device-wrapper">
                        <div class="device">
                            <div class="w-50">
                                   
                                <img src="~/logopreto.png" />

                            </div>
                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>